const modules=[
['Fundamentos, autores y corrientes de la Psicología',28,'Comprende cómo surgió la Psicología científica, descubre sus principales autores y diferencia las grandes escuelas que marcaron la disciplina.'],
['Neuropsicología y bases biológicas de la conducta',38,'Explora el sistema nervioso, las funciones cerebrales y la relación entre procesos biológicos, cognición y comportamiento.'],
['Cognición, memoria y aprendizaje',38,'Descubre cómo funcionan la atención, la percepción, la memoria y los principales procesos de aprendizaje y toma de decisiones.'],
['Psicología del desarrollo humano',33,'Comprende los cambios psicológicos desde la infancia hasta el envejecimiento y conoce teorías fundamentales del desarrollo.'],
['Personalidad y diferencias individuales',28,'Estudia los rasgos, el temperamento, el modelo Big Five y las principales perspectivas sobre la personalidad.'],
['Emoción, motivación y regulación emocional',33,'Comprende los procesos emocionales, la motivación, el estrés y los conceptos fundamentales de regulación emocional y afrontamiento.'],
['Psicología social y relaciones humanas',28,'Explora cómo los grupos, las relaciones, la comunicación y el contexto social influyen en los pensamientos y comportamientos.'],
['Psicopatología: Guía visual',33,'Conoce conceptos introductorios de psicopatología, diferentes patrones clínicos y principios de comprensión responsable de la salud mental.'],
['Evaluación psicológica y Psicometría',28,'Familiarízate con entrevistas, observación, fiabilidad, validez, percentiles y fundamentos de la medición psicológica.'],
['Recursos psicoeducativos y reflexión',38,'Explora conceptos relacionados con emociones, valores, hábitos, pensamiento y comportamiento desde una perspectiva educativa.'],
['Investigación, evidencia y metodología',28,'Comprende hipótesis, variables, métodos de investigación, estadística y los fundamentos del pensamiento científico.']];
const bonusValues=[12,10,9,10,9];
const bonuses=[['Diccionario Esencial de Psicología','Consulta términos y definiciones importantes cuando necesites recordar o aclarar conceptos durante tus estudios.'],['15 Grandes Autores de la Psicología','Conoce figuras que marcaron la disciplina, sus principales aportaciones y su influencia en diferentes corrientes.'],['Historia de la Psicología: Guía Rápida','Recorre momentos importantes de la evolución de la Psicología y comprende cómo surgieron sus principales enfoques.'],['10 Experimentos que Marcaron la Psicología','Explora investigaciones históricas relevantes, sus aportaciones y las cuestiones metodológicas y éticas que ayudan a interpretarlas.'],['Guía de Lecturas para Estudiantes de Psicología','Descubre orientaciones de lectura para seguir profundizando en diferentes autores, teorías y áreas de conocimiento.']];
const pains=[['Tienes demasiada información, pero poca organización.','Guardas guías, capturas, apuntes y documentos. Cuando necesitas un concepto específico, no recuerdas dónde encontrarlo.'],['Lees mucho, pero algunos conceptos siguen siendo confusos.','Pasas de una explicación a otra intentando comprender teorías que podrían presentarse de una forma más clara.'],['Pierdes tiempo reuniendo materiales para estudiar.','En lugar de comprender y repasar, terminas buscando fuentes, clasificando documentos y organizando apuntes.'],['Antes de una clase o examen, necesitas respuestas más rápidas.','Quieres revisar un autor, recordar una teoría o comparar conceptos, pero la información está dispersa.']];
const benefits=[['Encuentra conceptos sin buscar entre decenas de archivos.','Accede a módulos organizados para localizar los temas que quieras estudiar o repasar.'],['Comprende cómo se relacionan las diferentes áreas.','Conecta autores, cerebro, aprendizaje, emociones, personalidad y comportamiento.'],['Transforma el desorden en una ruta de estudio más clara.','Sigue una estructura temática que facilita tus sesiones de estudio.'],['Repasa antes de clases y exámenes.','Vuelve a consultar definiciones, teorías y conceptos como material complementario.'],['Lleva tu biblioteca contigo.','Consulta los archivos desde tu celular, tablet o computadora compatible.']];
const audience=[['Para estudiantes de Psicología','Un material visual complementario para revisar los principales temas de su formación.'],['Para quienes están comenzando','Familiarízate con los conceptos fundamentales antes de profundizar en libros especializados.'],['Para quienes necesitan repasar','Vuelve a consultar autores, teorías y conceptos sin buscar entre numerosos documentos.'],['Para personas interesadas en Psicología','Comprende mejor la disciplina mediante una introducción organizada y accesible.'],['Para quienes prefieren aprender de forma visual','Materiales estructurados, explicaciones claras y una organización por módulos.']];
const faqs=[['¿Cuál es la diferencia entre el Paquete Básico y el Completo?','Ambos incluyen la misma Biblioteca de Psicología con 11 módulos y 353 páginas. El Paquete Completo añade cinco libros digitales complementarios que no forman parte del Básico.'],['¿El paquete de US$ 5 incluye las 353 páginas?','Sí. El Paquete Básico incluye los 11 módulos y las 353 páginas de la biblioteca principal, pero no los cinco bonos adicionales.'],['¿Los cinco bonos están incluidos en el Paquete Completo?','Sí. Al adquirir el Paquete Completo por US$ 14,90, recibirás la biblioteca principal más los cinco materiales complementarios indicados en la oferta.'],['¿Recibiré libros físicos?','No. Todos los materiales se entregan exclusivamente en formato digital.'],['¿Cómo recibiré el material?','Después de confirmar el pago, recibirás las instrucciones para acceder a los materiales digitales adquiridos mediante la plataforma de entrega correspondiente.'],['¿Puedo consultar la biblioteca desde mi celular?','Sí. Puedes consultar las guías digitales desde tu celular, tablet o computadora compatible.'],['¿Necesito estudiar Psicología en la universidad?','No. La biblioteca está dirigida tanto a estudiantes como a personas interesadas en conocer los fundamentos de la disciplina.'],['¿Sustituye mis libros universitarios?','No. Es un material complementario de estudio, revisión y consulta. No reemplaza bibliografía especializada ni una formación académica formal.'],['¿Puedo utilizar el material para diagnosticar personas?','No. Los contenidos de psicopatología y evaluación tienen fines educativos y no habilitan para realizar diagnósticos ni intervenciones profesionales.'],['¿Hay pagos mensuales?','No. El precio anunciado corresponde a un pago único.'],['¿Cómo funciona la garantía?','La garantía es de 7 días, sujeta a las condiciones de reembolso informadas en el checkout.']];
const groups=[['Psicopatología',['Trastornos de personalidad','Ansiedad','Modelo biopsicosocial','Salud mental','Patrones clínicos']],['Psicopatología y Evaluación',['Psicosis','Espectro autista','Entrevista psicológica','Observación','Principios de evaluación']],['Psicometría y Recursos Psicoeducativos',['Validez','Fiabilidad','Percentiles','Escucha activa','Emociones']],['Recursos Psicoeducativos e Investigación',['Pensamiento y conducta','Valores','Hábitos','Hipótesis','Métodos de investigación']],['Metodología Científica',['Estudios correlacionales','Causalidad','Variables','Estadística','Pensamiento crítico']]];
const $=s=>document.querySelector(s);const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function cards(id,data){$(id).innerHTML=data.map(([t,d],i)=>`<article class="card"><span class="number">${String(i+1).padStart(2,'0')}</span><h3>${esc(t)}</h3><p>${esc(d)}</p></article>`).join('')}
cards('#pains',pains);cards('#benefits',benefits);cards('#audience',audience);
$('#modules').innerHTML=modules.map(([t,n,d],i)=>`<details><summary><span class="module-num">${String(i+1).padStart(2,'0')}</span><span class="module-title">${esc(t)}</span><span class="pages">${n} páginas</span></summary><p>${esc(d)}</p></details>`).join('');
$('#bonus-list').innerHTML=bonuses.map(([t,d],i)=>`<article class="bonus-row"><img src="/assets/bonus-${i+1}.webp" width="1024" height="1024" loading="lazy" alt="Portada digital: ${esc(t)}"><div><span class="number">BONO ${String(i+1).padStart(2,'0')}</span><h3>${esc(t)}</h3><p>${esc(d)}</p><div class="bonus-value"><span>Valor de referencia estimado</span><s>US$ ${bonusValues[i]}</s><strong>INCLUIDO</strong></div><p class="currency-note">Conversión automática a tu moneda local, según disponibilidad en el checkout.</p></div></article>`).join('');
$('#plan-bonuses').innerHTML=bonuses.map(([t])=>`<li>${esc(t)}</li>`).join('');
$('#faqs').innerHTML=faqs.map(([t,d])=>`<details><summary>${esc(t)}</summary><p>${esc(d)}</p></details>`).join('');
const sampleGroups=window.SAMPLE_PAGES;
$('#sample-nav').innerHTML=modules.map(([title],i)=>`<a href="#sample-group-${i+1}" title="${esc(title)}">${String(i+1).padStart(2,'0')}</a>`).join('');
$('#galleries').innerHTML=sampleGroups.map((samples,i)=>`<div class="gallery" id="sample-group-${i+1}"><div class="gallery-heading"><div><span class="eyebrow">MÓDULO ${String(i+1).padStart(2,'0')} · ${samples.length} MUESTRAS REALES</span><h3>${esc(modules[i][0])}</h3></div><div class="controls"><button data-dir="-1" aria-label="Muestras anteriores del módulo ${i+1}">‹</button><button data-dir="1" aria-label="Más muestras del módulo ${i+1}">›</button></div></div><div class="track" tabindex="0" aria-label="Muestras del módulo ${i+1}">${samples.map((x,j)=>`<button class="sample-card" data-sample="${sampleGroups.slice(0,i).reduce((n,g)=>n+g.length,0)+j}" aria-label="Ampliar ${esc(x.title)}, módulo ${i+1}, página ${x.page}"><img src="${x.thumb}" alt="Página real: ${esc(x.title)}" loading="lazy" decoding="async" width="${x.width}" height="${x.height}" draggable="false"><span class="sample-info"><strong>${esc(x.title)}</strong><span>Página ${x.page} · Toca para ampliar</span></span></button>`).join('')}</div></div>`).join('');
document.querySelectorAll('.gallery').forEach(g=>{const track=g.querySelector('.track');g.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>track.scrollBy({left:Number(b.dataset.dir)*315,behavior:'smooth'}));let startX,startScroll,active=false;track.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0)return;active=true;startX=e.clientX;startScroll=track.scrollLeft});track.addEventListener('pointermove',e=>{if(!active)return;const distance=e.clientX-startX;if(Math.abs(distance)>8&&!track.classList.contains('dragging')){track.setPointerCapture(e.pointerId);track.classList.add('dragging')}if(track.classList.contains('dragging'))track.scrollLeft=startScroll-distance});['pointerup','pointercancel','lostpointercapture'].forEach(type=>track.addEventListener(type,()=>{active=false;track.classList.remove('dragging')}))});
const checkout={basico:'https://pay.hotmart.com/Q107777532N?off=4qutgwgw',completo:'https://pay.hotmart.com/Q107777532N?off=bx4hzpp7',completo10:'https://pay.hotmart.com/Q107777532N?off=44eb48t5'};const dialog=$('#modal');let trigger;
function show(title,copy,button){trigger=button;$('#modal-title').textContent=title;$('#modal-copy').textContent=copy;dialog.showModal()}
const upgradeModal=$('#upgrade-modal');let upgradeTrigger;
$('#upgrade-bonuses').innerHTML=`<li>11 módulos completos · 353 páginas</li>`+bonuses.map(([title])=>`<li>${esc(title)}</li>`).join('');
function openUpgrade(button){upgradeTrigger=button;upgradeModal.showModal()}
function closeUpgrade(){upgradeModal.close();upgradeTrigger?.focus()}
function purchase(plan,price,key,button){const link=checkout[key];if(link){window.BibliotecaTracking?.initiateCheckout(price,plan);location.assign(window.BibliotecaTracking?window.BibliotecaTracking.checkoutUrl(link):link);return}show(`Paquete ${plan} · US$ ${price}`,'El enlace de compra de esta oferta estará disponible próximamente.',button)}
document.querySelectorAll('.buy').forEach(b=>b.onclick=e=>{e.stopPropagation();if(b.dataset.plan==='Básico'){openUpgrade(b);return}purchase('Completo',14.90,'completo',b)});
$('#basico').addEventListener('click',e=>{if(e.target.closest('a,button'))return;openUpgrade($('#basico'))});$('#basico').addEventListener('keydown',e=>{if(e.target===$('#basico')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openUpgrade($('#basico'))}});
$('.upgrade-close').onclick=closeUpgrade;
$('#accept-upgrade').onclick=()=>{upgradeModal.close();purchase('Completo',10,'completo10',upgradeTrigger)};
$('#decline-upgrade').onclick=()=>{upgradeModal.close();purchase('Básico',5,'basico',upgradeTrigger)};
upgradeModal.addEventListener('cancel',()=>upgradeTrigger?.focus());
const info={privacy:['Política de Privacidad','Esta página utiliza Meta Pixel y UTMify para medir visitas, clics y atribución de anuncios mediante cookies y parámetros de campaña. El pago se realiza en Hotmart y se aplica su política de privacidad. No solicitamos datos de pago en esta página.'],terms:['Términos de Uso','Oferta de materiales digitales para estudio y consulta educativa. El precio final, la moneda de cobro, las condiciones de acceso y de reembolso deben confirmarse en la página de pago antes de comprar. El material no habilita para diagnóstico ni intervención profesional.'],contact:['Contacto','Los datos de contacto del vendedor y el soporte de compra se indican en la página de pago de Hotmart y en la confirmación de tu pedido.']};document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>show(...info[b.dataset.info],b));
function closeModal(){dialog.close();trigger?.focus()}document.querySelectorAll('.close,.close-bottom').forEach(b=>b.onclick=closeModal);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
if('IntersectionObserver' in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('reveal');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.card,.bonus-row,.stats,.plan,.gallery').forEach(e=>io.observe(e))}

const allSamples=sampleGroups.flat();let sampleIndex=0,sampleTrigger,dragDistance=0;
const sampleModal=$('#sample-modal');
function renderSample(){const item=allSamples[sampleIndex];$('#sample-caption').textContent=`${item.title} · Módulo ${item.module} · Página ${item.page} · ${sampleIndex+1} / ${allSamples.length}`;const im=$('#sample-full');im.src=item.src;im.alt=`Página real del material: ${item.title}`;im.width=item.width;im.height=item.height;$('.lightbox-body').scrollTop=0;}
function closeSample(){sampleModal.close();sampleTrigger?.focus()}
document.querySelectorAll('.sample-card').forEach(b=>{let x=0;b.addEventListener('pointerdown',e=>{x=e.clientX;dragDistance=0});b.addEventListener('pointermove',e=>{if(e.buttons)dragDistance=Math.abs(e.clientX-x)});b.onclick=()=>{if(dragDistance>8)return;sampleIndex=Number(b.dataset.sample);sampleTrigger=b;renderSample();sampleModal.showModal()}});
$('#sample-prev').onclick=()=>{sampleIndex=(sampleIndex-1+allSamples.length)%allSamples.length;renderSample()};$('#sample-next').onclick=()=>{sampleIndex=(sampleIndex+1)%allSamples.length;renderSample()};$('.lightbox-close').onclick=closeSample;sampleModal.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();$('#sample-next').click()}if(e.key==='ArrowLeft'){e.preventDefault();$('#sample-prev').click()}});
sampleModal.addEventListener('click',e=>{if(e.target===sampleModal){const r=sampleModal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeSample()}});
