const modules=[["Fundamentos, autores y corrientes de la Psicología",28,"Origen, autores y principales corrientes de la Psicología."],["Neuropsicología y bases biológicas de la conducta",38,"Sistema nervioso, cerebro y bases biológicas de la conducta."],["Cognición, memoria y aprendizaje",38,"Atención, memoria, aprendizaje y toma de decisiones."],["Psicología del desarrollo humano",33,"Desarrollo psicológico desde la infancia hasta el envejecimiento."],["Personalidad y diferencias individuales",28,"Rasgos, temperamento y modelos de personalidad."],["Emoción, motivación y regulación emocional",33,"Emociones, motivación, estrés y afrontamiento."],["Psicología social y relaciones humanas",28,"Grupos, comunicación y relaciones humanas."],["Psicopatología: Guía visual",33,"Conceptos introductorios para comprender la salud mental."],["Evaluación psicológica y Psicometría",28,"Entrevistas, fiabilidad, validez y medición psicológica."],["Recursos psicoeducativos y reflexión",38,"Emociones, valores, hábitos y reflexión educativa."],["Investigación, evidencia y metodología",28,"Hipótesis, variables, estadística y pensamiento científico."]];
const bonusValues=[12,10,9,10,9];
const bonuses=[["Diccionario Esencial de Psicología","Aclara términos y definiciones durante tus estudios."],["15 Grandes Autores de la Psicología","Descubre sus ideas y aportaciones principales."],["Historia de la Psicología: Guía Rápida","Conoce los momentos clave de la disciplina."],["10 Experimentos que Marcaron la Psicología","Revisa sus aportaciones, límites y cuestiones éticas."],["Guía de Lecturas para Estudiantes de Psicología","Encuentra lecturas para seguir profundizando."]];
const pains=[["Demasiados archivos, poca organización.","Encuentra tus conceptos sin revisar decenas de documentos."],["Explicaciones que siguen siendo confusas.","Consulta los fundamentos con una estructura visual."],["Horas reuniendo materiales.","Dedica más tiempo a comprender y repasar."],["Necesitas repasar con rapidez.","Vuelve a consultar lo esencial antes de clase."]];
const benefits=[["Encuentra conceptos rápidamente.","Consulta temas organizados en 11 módulos."],["Conecta las distintas áreas.","Relaciona cerebro, emociones, aprendizaje y conducta."],["Ordena tus sesiones de estudio.","Sigue una estructura temática clara."],["Repasa cuando lo necesites.","Revisa conceptos antes de clases y exámenes."],["Lleva tu biblioteca contigo.","Consulta las guías en dispositivos compatibles."]];
const audience=[["Estudiantes de Psicología","Material visual para complementar tus estudios."],["Quienes están comenzando","Una introducción organizada a los fundamentos."],["Quienes necesitan repasar","Autores, teorías y conceptos a mano."],["Personas interesadas en Psicología","Explora la disciplina de forma accesible."],["Quienes aprenden de forma visual","Explicaciones estructuradas por temas."]];
const faqs=[["¿Qué cambia entre Básico y Completo?","Ambos incluyen 11 módulos y 353 páginas. El Completo añade los 5 bonos digitales."],["¿El Básico de US$ 5 incluye toda la biblioteca?","Sí: los 11 módulos y las 353 páginas, sin bonos."],["¿El Completo incluye los 5 bonos?","Sí. Por US$ 14,90 recibes la biblioteca y los cinco bonos anunciados."],["¿Recibiré libros físicos?","No. Todos los materiales son digitales."],["¿Cómo recibo el material?","Tras confirmar el pago, recibirás las instrucciones de acceso."],["¿Puedo consultarlo desde mi celular?","Sí, desde celulares, tablets y computadoras compatibles."],["¿Necesito estudiar Psicología?","No. También puedes usarlo para conocer los fundamentos."],["¿Sustituye mis libros universitarios?","No. Es material complementario, no reemplaza bibliografía especializada ni formación académica."],["¿Sirve para diagnosticar personas?","No. Su finalidad es educativa y no habilita para diagnosticar ni intervenir profesionalmente."],["¿Hay mensualidades?","No. Es un pago único."],["¿Cómo funciona la garantía?","Tienes 7 días, sujetos a las condiciones de reembolso del checkout."]];
const groups=[['Psicopatología',['Trastornos de personalidad','Ansiedad','Modelo biopsicosocial','Salud mental','Patrones clínicos']],['Psicopatología y Evaluación',['Psicosis','Espectro autista','Entrevista psicológica','Observación','Principios de evaluación']],['Psicometría y Recursos Psicoeducativos',['Validez','Fiabilidad','Percentiles','Escucha activa','Emociones']],['Recursos Psicoeducativos e Investigación',['Pensamiento y conducta','Valores','Hábitos','Hipótesis','Métodos de investigación']],['Metodología Científica',['Estudios correlacionales','Causalidad','Variables','Estadística','Pensamiento crítico']]];
const $=s=>document.querySelector(s);const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function cards(id,data){$(id).innerHTML=data.map(([t,d],i)=>`<article class="card"><span class="number">${String(i+1).padStart(2,'0')}</span><h3>${esc(t)}</h3><p>${esc(d)}</p></article>`).join('')}
cards('#pains',pains);cards('#benefits',benefits);cards('#audience',audience);
$('#modules').innerHTML=modules.map(([t,n,d],i)=>`<details><summary><span class="module-num">${String(i+1).padStart(2,'0')}</span><span class="module-title">${esc(t)}</span><span class="pages">${n} páginas</span></summary><p>${esc(d)}</p></details>`).join('');
$('#bonus-list').innerHTML=bonuses.map(([t,d],i)=>`<article class="bonus-row"><img src="/assets/bonus-${i+1}.webp" width="1024" height="1024" loading="lazy" alt="Portada digital: ${esc(t)}"><div><span class="number">BONO ${String(i+1).padStart(2,'0')}</span><h3>${esc(t)}</h3><p>${esc(d)}</p><div class="bonus-value"><span>Valor de referencia estimado</span><s>US$ ${bonusValues[i]}</s><strong>INCLUIDO</strong></div><p class="currency-note">Conversión automática a tu moneda local, según disponibilidad en el checkout.</p></div></article>`).join('');
$('#plan-bonuses').innerHTML=bonuses.map(([t])=>`<li>${esc(t)}</li>`).join('');
$('#faqs').innerHTML=faqs.map(([t,d])=>`<details><summary>${esc(t)}</summary><p>${esc(d)}</p></details>`).join('');
const samplePages=window.SAMPLE_PAGES.flat();
const sampleGroups=Array.from({length:5},(_,i)=>samplePages.slice(i*10,(i+1)*10));
$('#galleries').innerHTML=sampleGroups.map((samples,i)=>`<div class="gallery" id="sample-group-${i+1}"><div class="gallery-heading"><div class="controls"><button data-dir="-1" aria-label="Muestras anteriores del carrusel ${i+1}">‹</button><button data-dir="1" aria-label="Más muestras del carrusel ${i+1}">›</button></div></div><div class="track" tabindex="0" aria-label="Carrusel de muestras ${i+1}">${samples.map((x,j)=>`<button class="sample-card" data-sample="${i*10+j}" aria-label="Ampliar muestra ${i*10+j+1}"><img src="${x.thumb}" alt="Muestra ${i*10+j+1} de la biblioteca" loading="lazy" decoding="async" width="${x.width}" height="${x.height}" draggable="false"></button>`).join('')}</div></div>`).join('');
document.querySelectorAll('.gallery').forEach(g=>{const track=g.querySelector('.track');g.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>track.scrollBy({left:Number(b.dataset.dir)*315,behavior:'smooth'}));let startX,startScroll,active=false;track.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0)return;active=true;startX=e.clientX;startScroll=track.scrollLeft});track.addEventListener('pointermove',e=>{if(!active)return;const distance=e.clientX-startX;if(Math.abs(distance)>8&&!track.classList.contains('dragging')){track.setPointerCapture(e.pointerId);track.classList.add('dragging')}if(track.classList.contains('dragging'))track.scrollLeft=startScroll-distance});['pointerup','pointercancel','lostpointercapture'].forEach(type=>track.addEventListener(type,()=>{active=false;track.classList.remove('dragging')}))});
const checkout={basico:'https://pay.hotmart.com/Q107777532N?off=4qutgwgw',completo:'https://pay.hotmart.com/Q107777532N?off=bx4hzpp7',completo10:'https://pay.hotmart.com/Q107777532N?off=44eb48t5'};const dialog=$('#modal');let trigger;
function show(title,copy,button){trigger=button;$('#modal-title').textContent=title;$('#modal-copy').textContent=copy;dialog.showModal()}
const upgradeModal=$('#upgrade-modal');let upgradeTrigger;
$('#upgrade-bonuses').innerHTML=`<li>11 módulos completos · 353 páginas</li>`+bonuses.map(([title])=>`<li>${esc(title)}</li>`).join('');
function openUpgrade(button){upgradeTrigger=button;upgradeModal.showModal()}
function closeUpgrade(){upgradeModal.close();upgradeTrigger?.focus()}
function purchase(plan,price,key,button){const link=checkout[key];if(link){window.BibliotecaTracking?.initiateCheckout(price,plan);location.assign(window.BibliotecaTracking?window.BibliotecaTracking.checkoutUrl(link):link);return}show(`Paquete ${plan} · US$ ${price}`,'El enlace de compra de esta oferta estará disponible próximamente.',button)}
document.querySelectorAll('.buy').forEach(b=>b.onclick=e=>{e.stopPropagation();if(b.dataset.plan==='Básico'){openUpgrade(b);return}purchase('Completo',14.90,'completo',b)});
$('#basico').addEventListener('click',e=>{if(e.target.closest('a,button'))return;openUpgrade($('#basico'))});$('#basico').addEventListener('keydown',e=>{if(e.target===$('#basico')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openUpgrade($('#basico'))}});
$('.upgrade-close').onclick=closeUpgrade;
$('#accept-upgrade').onclick=()=>{upgradeModal.close();purchase('Completo',10,'completo10',upgradeTrigger)};
$('#decline-upgrade').onclick=()=>{upgradeModal.close();purchase('Básico',5,'basico',upgradeTrigger)};
upgradeModal.addEventListener('cancel',()=>upgradeTrigger?.focus());
const info={privacy:['Política de Privacidad','Esta página utiliza Meta Pixel y UTMify para medir visitas, clics y atribución de anuncios mediante cookies y parámetros de campaña. El pago se realiza en Hotmart y se aplica su política de privacidad. No solicitamos datos de pago en esta página.'],terms:['Términos de Uso','Oferta de materiales digitales para estudio y consulta educativa. El precio final, la moneda de cobro, las condiciones de acceso y de reembolso deben confirmarse en la página de pago antes de comprar. El material no habilita para diagnóstico ni intervención profesional.'],contact:['Contacto','Los datos de contacto del vendedor y el soporte de compra se indican en la página de pago de Hotmart y en la confirmación de tu pedido.']};document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>show(...info[b.dataset.info],b));
function closeModal(){dialog.close();trigger?.focus()}document.querySelectorAll('.close,.close-bottom').forEach(b=>b.onclick=closeModal);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
if('IntersectionObserver' in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('reveal');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.card,.bonus-row,.stats,.plan,.gallery').forEach(e=>io.observe(e))}

const allSamples=sampleGroups.flat();let sampleIndex=0,sampleTrigger,dragDistance=0;
const sampleModal=$('#sample-modal');
function renderSample(){const item=allSamples[sampleIndex];$('#sample-caption').textContent=`Muestra ${sampleIndex+1} de ${allSamples.length}`;const im=$('#sample-full');im.src=item.src;im.alt=`Muestra ${sampleIndex+1} de la biblioteca`;im.width=item.width;im.height=item.height;$('.lightbox-body').scrollTop=0;}
function closeSample(){sampleModal.close();sampleTrigger?.focus()}
document.querySelectorAll('.sample-card').forEach(b=>{let x=0;b.addEventListener('pointerdown',e=>{x=e.clientX;dragDistance=0});b.addEventListener('pointermove',e=>{if(e.buttons)dragDistance=Math.abs(e.clientX-x)});b.onclick=()=>{if(dragDistance>8)return;sampleIndex=Number(b.dataset.sample);sampleTrigger=b;renderSample();sampleModal.showModal()}});
$('#sample-prev').onclick=()=>{sampleIndex=(sampleIndex-1+allSamples.length)%allSamples.length;renderSample()};$('#sample-next').onclick=()=>{sampleIndex=(sampleIndex+1)%allSamples.length;renderSample()};$('.lightbox-close').onclick=closeSample;sampleModal.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();$('#sample-next').click()}if(e.key==='ArrowLeft'){e.preventDefault();$('#sample-prev').click()}});
sampleModal.addEventListener('click',e=>{if(e.target===sampleModal){const r=sampleModal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeSample()}});
